name: Deploy to Ubuntu Server

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone code to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd bungie-bot
            git pull origin main

      - name: Rebuild Docker Container and Start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd bungie-bot
            docker stop bungie-bot || true
            docker rm bungie-bot || true
            docker build -t bungie-bot .
            docker run -d --name bungie-bot bungie-bot
